/**
 * Generator for the CSR assets the C++ port composites: the 32 Halo 5 division
 * emblems (assets/csr-*.png) and the two Blender Pro typefaces
 * (assets/fonts/BlenderPro-{Medium,Bold}.ttf). Bakes their bytes into
 * cpp/src/csr_assets.h so the shipped exe needs no asset files on disk — the
 * same approach genMedalAssets.ts uses for the podium medals.
 *
 * The TS renderers read the PNGs/TTFs straight from assets/; the C++ renderers
 * read these embedded copies. Re-run whenever the emblem art or fonts change:
 *
 *   npx tsx src/genCsrAssets.ts
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

// Emblem keys, matching the `emblem` field on a Csr (csr.ts) + the Champion
// insignia. These are the assets/csr-<key>.png files (also used by csrEmblems.ts).
const SUB_TIERS = ["bronze", "silver", "gold", "platinum", "diamond"];
const EMBLEM_KEYS = [
  ...SUB_TIERS.flatMap((t) => [1, 2, 3, 4, 5, 6].map((n) => `${t}-${n}`)),
  "onyx",
  "champion",
];

const asset = (rel: string): Buffer =>
  readFileSync(fileURLToPath(new URL(`../assets/${rel}`, import.meta.url)));

function cppBytes(data: Buffer): string {
  const lines: string[] = [];
  for (let i = 0; i < data.length; i += 16) {
    const chunk = [...data.subarray(i, i + 16)].map((b) => `0x${b.toString(16).padStart(2, "0")},`);
    lines.push(`    ${chunk.join(" ")}`);
  }
  return lines.join("\n");
}

/** A C identifier for an emblem key, e.g. "diamond-5" -> "CSR_EMB_diamond_5". */
const symbol = (key: string): string => `CSR_EMB_${key.replace(/-/g, "_")}`;

const emblems = EMBLEM_KEYS.map((key) => ({ key, png: asset(`csr-${key}.png`) }));
const fontMedium = asset("fonts/BlenderPro-Medium.ttf");
const fontBold = asset("fonts/BlenderPro-Bold.ttf");

const header = `// GENERATED by src/genCsrAssets.ts — do not edit by hand.
// Baked bytes of the Halo 5 CSR division emblems (assets/csr-*.png) and the two
// Blender Pro typefaces (MCC's UI font), so the exe needs no asset files.
#pragma once
#include <cstddef>

${emblems
  .map(
    (e) => `inline const unsigned char ${symbol(e.key)}[] = {
${cppBytes(e.png)}
};`,
  )
  .join("\n\n")}

struct CsrEmblemAsset {
    const char* key;
    const unsigned char* data;
    size_t size;
};

inline const CsrEmblemAsset CSR_EMBLEM_ASSETS[] = {
${emblems.map((e) => `    {"${e.key}", ${symbol(e.key)}, sizeof(${symbol(e.key)})},`).join("\n")}
};

inline const unsigned char BLENDER_PRO_MEDIUM[] = {
${cppBytes(fontMedium)}
};

inline const unsigned char BLENDER_PRO_BOLD[] = {
${cppBytes(fontBold)}
};
`;

writeFileSync(fileURLToPath(new URL("../cpp/src/csr_assets.h", import.meta.url)), header);

const total =
  emblems.reduce((n, e) => n + e.png.length, 0) + fontMedium.length + fontBold.length;
console.log(
  `wrote cpp/src/csr_assets.h — ${emblems.length} emblems + 2 fonts (${total} bytes embedded)`,
);
