/**
 * Generator for the podium-medal images used by the leaderboard PNG.
 *
 * Rasterises 🥇🥈🥉 (Segoe UI Emoji) once into small transparent PNGs so both
 * renderers composite identical pixels: the Node renderer reads
 * assets/medal-{1,2,3}.png, and the C++ port embeds the same bytes via the
 * generated cpp/src/medal_assets.h (GDI+ cannot draw colour emoji fonts, and
 * baked images also keep the exe free of font dependencies).
 *
 * Re-run only if the medal look should change:
 *
 *   npx tsx src/genMedalAssets.ts
 */

import { createCanvas } from "@napi-rs/canvas";
import { mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const SIZE = 96; // rendered large, drawn downscaled for clean edges
const MEDALS = ["🥇", "🥈", "🥉"];

function renderMedal(emoji: string): Buffer {
  const canvas = createCanvas(SIZE, SIZE);
  const ctx = canvas.getContext("2d");
  ctx.font = '84px "Segoe UI Emoji"';
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillText(emoji, SIZE / 2, SIZE / 2);
  return canvas.toBuffer("image/png");
}

function cppBytes(data: Buffer): string {
  const lines: string[] = [];
  for (let i = 0; i < data.length; i += 16) {
    const chunk = [...data.subarray(i, i + 16)].map((b) => `0x${b.toString(16).padStart(2, "0")},`);
    lines.push(`    ${chunk.join(" ")}`);
  }
  return lines.join("\n");
}

const pngs = MEDALS.map(renderMedal);

const assetsDir = fileURLToPath(new URL("../assets/", import.meta.url));
mkdirSync(assetsDir, { recursive: true });
pngs.forEach((png, i) => writeFileSync(`${assetsDir}medal-${i + 1}.png`, png));

const header = `// GENERATED by src/genMedalAssets.ts — do not edit by hand.
// PNG bytes of the 🥇🥈🥉 podium medals composited onto the leaderboard image
// (GDI+ cannot render colour emoji fonts, so the glyphs are baked once).
#pragma once
#include <cstddef>

${pngs
  .map(
    (png, i) => `inline const unsigned char MEDAL_PNG_${i + 1}[] = {
${cppBytes(png)}
};`,
  )
  .join("\n\n")}

struct MedalAsset {
    const unsigned char* data;
    size_t size;
};

inline const MedalAsset MEDAL_ASSETS[3] = {
    {MEDAL_PNG_1, sizeof(MEDAL_PNG_1)},
    {MEDAL_PNG_2, sizeof(MEDAL_PNG_2)},
    {MEDAL_PNG_3, sizeof(MEDAL_PNG_3)},
};
`;

writeFileSync(fileURLToPath(new URL("../cpp/src/medal_assets.h", import.meta.url)), header);
console.log(
  `wrote assets/medal-{1,2,3}.png and cpp/src/medal_assets.h (${pngs
    .map((p) => p.length)
    .join(", ")} bytes)`,
);
